### ISSUE TITLE
Extension always displaying off (disabled)

### ISSUE THREAD

**Issue by joeroback** [badsgahhl/pihole-browser-extension#54]
Pi-hole v5.8.1
FTL v5.13
Web Interface v5.10.1

basically i think the call to /admin/api.php has changed, such that this extension no longer correctly see pihole as running.

**Comment by JeromeX** [comment]
same here, after update to the latest version. It shows off but it's still on

![image](https://user-images.githubusercontent.com/15369779/148306990-8d00f1f8-df7f-4c62-9be7-7e8307caf3f3.png)
![image](https://user-images.githubusercontent.com/15369779/148307066-6aac5a77-4c3c-46f1-b609-ddc372d90586.png)
![image](https://user-images.githubusercontent.com/15369779/148307117-016d241c-997a-44cc-8bb1-e1fe73c6b295.png)

**Comment by joeroback** [comment]
I just filed this: https://github.com/pi-hole/AdminLTE/issues/2051

unclear what the API call should be, since its not documented, that being said, my PiHole iOS app is working fine with the latest updates...

**Comment by badsgahhl** [comment]
Oh wow. Thanks for reporting that. This will be fixed with v3.0.1.

**Comment by badsgahhl** [comment]
Still broken. Now disabled is shown wrong -> https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1006836175

**Comment by badsgahhl** [comment]
3.0.2. now reverts the changes from 3.0.1.

Extension should be fixed alongside with a new PiHole version upcoming the next days.

**Comment by rezzorix** [comment]
Why not keeping the issue "open" as long as it is not fixed-> imp[lemented (means error gone for the users).
Otherwise you will get just more and more issues opened up here... I was about to, but checked out the closed issues...

**Comment by badsgahhl** [comment]
Good idea. The text on the main page is kinda invisible.

**Comment by rezzorix** [comment]
> Good idea. The text on the main page is kinda invisible.

Also the settings page -> trouble shooting of the extension directs you to the "issues page" here on github (at least for Firefox, dont know about other browsers).
So naturally people wont necessary see the indeed almost invisible note about the bug on main page 😉

**Comment by eugef66** [comment]
Same problem. Stopped working after pihole latest update

**Comment by joeroback** [comment]
> Same problem. Stopped working after pihole latest update

well nothing has changed, pi-hole hasn't yet released the fix, and  the browser will forcefully update the extension 🤷🏼

**Comment by holocronology** [comment]
Also still seeing this issue.

PiHole Browser Extension: 3.0.2
Browser: Mozilla Firefox 96.0

**Comment by jkbdco** [comment]
Same issue on both Firefox and Chrome:

PiHole Browser Extension: 3.0.2
Operating System: Linux x86_64
Browser: Mozilla Firefox 91.0

PiHole Browser Extension: 3.0.2
Operating System: Linux x86_64
Browser: Chrome/Chromium 96.0.4664.110

**Comment by badsgahhl** [comment]
Yes the issue is known. Please be patient until PiHole releases a new version.

**Comment by eugef66** [comment]
> Yes the issue is known. Please be patient until PiHole releases a new version.

I didn't realize the issue is on PiHole end. It was not clear from this ticket. I was under impression that PiHole made some API changes and extension code need to be adjusted.  

Anyways, will wait for a PiHole update and hope it will fix the problem.

**Comment by parth115** [comment]
> Yes the issue is known. Please be patient until PiHole releases a new version. 
Is there a bug report in pihole repo ? Will be really helpful to track the bug there so that we can know when the fix is released.

**Comment by holocronology** [comment]
Same here...I didn't quite get that it was a pihole itself issue at first.

**Comment by fr4nk2342** [comment]
I don't know what they do differently, but maybe it helps.

The Android-App "Flutterhole" and the "Homeassistant Integration" are both working with the current PiHole version. Both are showing the correct status.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/7665987/149770053-2f611818-150e-4822-bd6e-c70643b89a7c.png">

https://play.google.com/store/apps/details?id=sterrenburg.github.flutterhole&hl=gsw&gl=US
https://www.home-assistant.io/integrations/pi_hole/

**Comment by rezzorix** [comment]
I agree, weird that other apps work but the extension doesnt... maybe they have a work-around that the extension dev doesnt?

In any case, the bug is known and was fixed by the pihole team, mentioned here: https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1006973367

It will be available to everyone with the next pihole update, which will be coming "soon" - see: https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1011208903

So nothing else to do other than wait I guess...

**Comment by nagaden2** [comment]
Just sent you 10 euros for your troubles. Thanks!

**Comment by badsgahhl** [comment]
> I don't know what they do differently, but maybe it helps.
> 
> The Android-App "Flutterhole" and the "Homeassistant Integration" are both working with the current PiHole version. Both are showing the correct status.

Don't use one of them. However, for instance Flutterhole also has an open issue about this bug.
https://github.com/sterrenburg/flutterhole/issues/158

> Just sent you 10 euros for your troubles. Thanks!

Thanks for your support 🙌

**Comment by joeroback** [comment]
it is quite annoying the pihole breaks the API with a regression for 2 weeks+ and doesn't do a hotfix if they are not ready for a full release... such is free and open source tho :)

**Comment by holocronology** [comment]
For those looking for a work around until this is fixed "soon" ... You can create a temporary bookmark with this process:  https://discourse.pi-hole.net/t/is-there-an-api-command-to-disable-ad-blocking/7693/2

**Comment by eugef66** [comment]
I just did some testing on my PiHole and I don't see an issue with pihole api and now confused my extension is not working. In my case the "status" attribute correctly reflects current status of pihole, but extension is still showing "off"

![image](https://user-images.githubusercontent.com/11634504/150386444-fb00bd86-a18a-404b-83f2-641056ffe999.png)

![image](https://user-images.githubusercontent.com/11634504/150386531-9e95f6c3-9ddd-4c5c-9bcf-09d8ca1f9b51.png)

![image](https://user-images.githubusercontent.com/11634504/150386738-5bdd3a0e-9cca-4f3d-ba5e-2fa3f83f0d0f.png)

![image](https://user-images.githubusercontent.com/11634504/150386801-99aff388-791b-47c1-a687-a233a134f805.png)

![image](https://user-images.githubusercontent.com/11634504/150386993-393fe0e3-dcb8-4243-9f20-fc16de18757e.png)

**Comment by joeroback** [comment]
please see https://github.com/pi-hole/AdminLTE/issues/2051

that changed the API call, previously it was `api.php?status` but currently its `api.php`  which is a bug, because there is still code that wants to use `status` query parameter, but the code is broken, it just happens to work when you leave it off (by accident)

**Comment by eugef66** [comment]
> please see [pi-hole/AdminLTE#2051](https://github.com/pi-hole/AdminLTE/issues/2051)
> 
> that changed the API call, previously it was `api.php?status` but currently its `api.php` which is a bug, because there is still code that wants to use `status` query parameter, but the code is broken, it just happens to work when you leave it off (by accident)

Ah-ha I see. Tested with a query parameter and I can confirm it returns "disabled", when pihole is active.

**Comment by stephan1827** [comment]
Is there any solution for this?

**Comment by badsgahhl** [comment]
> Is there any solution for this?

Nope. We can only wait for the PiHole Update 🙃 Soon....

**Comment by christasich** [comment]
> Is there any solution for this?

The fix has been merged into the development branch of pihole as noted [here](https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1006973367). You can check it out on your installation using `pihole checkout web devel`. If you run into any issues, you can always revert using `pihole checkout master`.

**Comment by user897943** [comment]
Still not fixed. Showing off/disabled even though it's definitely enabled. There is even a message on the extension settings saying that it is connected to the API

**Comment by rezzorix** [comment]
> Still not fixed. Showing off/disabled even though it's definitely enabled. There is even a message on the extension settings saying that it is connected to the API
> 
> ps. I meant on the master. I did the web devel and pihole -up, it's working now. When can I revert back to master? Or is it safe to leave as web devel?

What is so difficult to understand that it is a bug in api.php that has been fixed by the pihole team already but will only be available with the next offical pihole update?

Again: the bug is on pihole (official) side, not with the extension.

> In any case, the bug is known and was fixed by the pihole team, mentioned here: [pi-hole/AdminLTE#2051 (comment)](https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1006973367)
> 
> It will be available to everyone with the next pihole update, which will be coming "soon" - see: [pi-hole/AdminLTE#2051 (comment)](https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1011208903)

Ignoring facts & information that are widely available and then complaining about issues seems to be en vogue nowadays...

**Comment by user897943** [comment]
> 

Ok diva. Here's your chance to give another thumbs down so you can feel better!

**Comment by badsgahhl** [comment]
> > 
> 
> Ok diva. Here's your chance to give another thumbs down so you can feel better!

Calling others a diva shows great maturity when you can't get it together to read comments.

**Comment by user897943** [comment]
> > > 
> > 
> > 
> > Ok diva. Here's your chance to give another thumbs down so you can feel better!
> 
> Calling others a diva shows great maturity when you can't get it together to read comments.

Another diva 😂 yeah, never mind all the other stuff about me and my achievements that you don't know, I'm the recipient of a rant and the guy isn't a diva, and I'm immature... Alllllright lol. It's an internet comment about an ad blocker, don't be so sensitive.

**Comment by guice** [comment]
> Ok diva. Here's your chance to give another thumbs down so you can feel better!

I’m going to defend @rezzorix here and point out you should have read the thread before commenting. It’s just common courtesy to get background on the issue before filing a complaint it wasn’t completed.

**Comment by eugef66** [comment]
> > Ok diva. Here's your chance to give another thumbs down so you can feel better!
> 
> I’m going to defend @rezzorix here and point out you should have read the thread before commenting. It’s just common courtesy to get background on the issue before filing a complaint it wasn’t completed.

me too. Completely agree with above

**Comment by badsgahhl** [comment]
Fixed with https://github.com/pi-hole/AdminLTE/releases/tag/v5.11

**Comment by n3roGit** [comment]
![image](https://user-images.githubusercontent.com/8565847/161255647-fa23e0bb-5429-4399-b16f-982a935201ad.png)
![image](https://user-images.githubusercontent.com/8565847/161255675-f5c981a8-244b-471f-acba-93e5ec8d8bc8.png)


I have now switched to dev. unfortunately it still does not work :( Am I still doing something wrong?

**Comment by badsgahhl** [comment]
> ![image](https://user-images.githubusercontent.com/8565847/161255647-fa23e0bb-5429-4399-b16f-982a935201ad.png) ![image](https://user-images.githubusercontent.com/8565847/161255675-f5c981a8-244b-471f-acba-93e5ec8d8bc8.png)
> 
> I have now switched to dev. unfortunately it still does not work :( Am I still doing something wrong?

Normally it should just work with the latest PiHole version. No dev channel needed.

**Comment by n3roGit** [comment]
No Its not working for me :(

**Comment by n3roGit** [comment]
Any News?

**Comment by eugef66** [comment]
> Any News?

It’s working for everyone else after latest pi-hole upgrade. I’m sure it’s your local issue. Try re-installing extension and make sure pinhole is the latest version.

**Comment by n3roGit** [comment]
I have done all this things

**Comment by n3roGit** [comment]
Still not working with this version:
![image](https://user-images.githubusercontent.com/8565847/165503537-f8e84b48-044a-4235-8cc3-84a944f1cced.png)
i dont know whats wrong.
